#ifndef DC_WINDOW_MANAGER_PAGE_H
#define DC_WINDOW_MANAGER_PAGE_H

#include <gtk/gtk.h>

typedef struct _DcWindowManagerPage DcWindowManagerPage;

DcWindowManagerPage *dc_window_manager_page_new(void);
void dc_window_manager_page_free(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_widget(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_floating_mode_switch(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_snap_threshold_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_snap_show_preview_switch(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_layout_combo(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_border_width_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_focused_border_color_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_normal_border_color_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_window_gap_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_top_padding_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_bottom_padding_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_focus_opacity_switch(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_inactive_opacity_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_active_opacity_scale(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_add_desktop_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_add_desktop_button(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_rename_desktop_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_rename_desktop_button(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_remove_desktop_button(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_rule_app_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_rule_desktop_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_rule_state_combo(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_add_rule_button(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_remove_rule_entry(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_remove_rule_button(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_refresh_rules_button(DcWindowManagerPage *page);
GtkWidget *dc_window_manager_page_get_rules_text_view(DcWindowManagerPage *page);

#endif
